### PR TITLE
Created a cooldown system for commands (per user per cmd)

### PR DESCRIPTION
**Pull request by ItsLever**
As of right now I have left all the method overrides for cooldown per function at 0 meaning that they have no cooldown, please feel free to put whatever cooldowns you want per function.

If you want to change the message given or change something about the embed, its right before the return statement above the run call in Manager class

### CODE REVIEW

**Review by BooleanCube — CHANGES_REQUESTED** [review]
instead of doing it twice for guild commands and user commands, just do it a single time in the listener function.

**Comment by ItsLever** [comment]
aight sure

**Comment by ItsLever** [comment]
Alright I kept it in manager just for ease of access to the maps but instead put it once outside of the scope of else if for the guild/user commands, tested and works fine

**Review by BooleanCube — APPROVED** [review]
good stuff, this works.

**Pull request merged**
